# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Melle Dijkstra'
tagline: 'A place of thought'
# titleSuffix: ' · Melle Dijkstra'
email: dev.melle@gmail.com
description: 'A place of thought'
# >- # this means to ignore newlines until "baseurl:"
# Learn anything about science related topics. This is is where I share my latest ideas.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://melledijkstra.github.io" # the base hostname & protocol for your site, e.g. http://example.com
disqusId: "live-melledijkstra"

excerpt_separator: <!--more-->

collections_dir: collections

# Collections
collections:
    science:
        output: true
        permalink: /:collection/:title
#    lifestyle:
#        output: true
#        permalink: /:collection/:title
#    thoughts:
#        output: true
#        permalink: /:collection/:title

defaults:
    -   scope:
            path: "" # an empty string means all files in the project
            type: "science"
        values:
            layout: "story"
    -   scope:
            path: ""
            type: "lifestyle"
        values:
            layout: "story"
    -   scope:
            path: "files"
        values:
            sitemap: false
    -   scope:
            path: "sketches"
        values:
            sitemap: false

# Build settings
# theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    # - jekyll-paginate

#
#  PLUGIN CONFIGURATION
#

# - jekyll-paginate
# paginate: 30
# paginate-path: "/stories/page:num/"

# jekyll-seo-tag
webmaster_verifications:
    google: 'ofJ-CvPrDlbbef873pn7tx4OAxwtGGmaoDi-f1D2pz4'
    bing: 'A257B38ED344E8B133674B441B888037'
#    alexa: 1234
#    yandex: 1234
#    baidu: 1234

author:
    name: Melle Dijkstra

logo: '/assets/images/logo.png'

social:
    name: Melle Dijkstra
    links:
        - https://www.linkedin.com/in/melledijkstra
        - https://github.com/melledijkstra

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - project-files/
    - .idea/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# KramdownPermalink
    #Kramdown is the default Markdown renderer for Jekyll. Below is a list of the currently supported options:
    #
kramdown:
    # Prefix used for automatically generated header IDs
    # auto_id_prefix: ''
    # auto_id_stripping - Strip all formatting from header text for automatic ID generation
    # auto_ids - Use automatic header ID generation
    # coderay_bold_every - Defines how often a line number should be made bold
    # coderay_css - Defines how the highlighted code gets styled
    # coderay_default_lang - Sets the default language for highlighting code blocks
    # coderay_line_number_start - The start value for the line numbers
    # coderay_line_numbers - Defines how and if line numbers should be shown
    # coderay_tab_width - The tab width used in highlighted code
    # coderay_wrap - Defines how the highlighted code should be wrapped
    # enable_coderay - Use coderay for syntax highlighting
    # entity_output - Defines how entities are output
    # footnote_backlink - Defines the text that should be used for the footnote backlinks
    # footnote_backlink_inline - Specifies whether the footnote backlink should always be inline
    # footnote_nr - The number of the first footnote
    # gfm_quirks - Enables a set of GFM specific quirks
    # hard_wrap - Interprets line breaks literally
    # header_offset - Sets the output offset for headers
    # html_to_native - Convert HTML elements to native elements
    # line_width - Defines the line width to be used when outputting a document
    # link_defs - Pre-defines link definitions
    # math_engine - Set the math engine
    # math_engine_opts - Set the math engine options
    # parse_block_html: true # - Process kramdown syntax in block HTML tags
    # parse_span_html - Process kramdown syntax in span HTML tags
    # smart_quotes - Defines the HTML entity names or code points for smart quote output
    # syntax_highlighter - Set the syntax highlighter
    # syntax_highlighter_opts - Set the syntax highlighter options
    # toc_levels - Defines the levels that are used for the table of contents
    # transliterated_header_ids - Transliterate the header text before generating the ID
    # typographic_symbols - Defines a mapping from typographical symbol to output characters

